name: react
version: 5.1.0-dev.0
authors:
  - Samuel Hapák <samuel.hapak@gmail.com>
  - Greg Littlefield <greg.littlefield@workiva.com>
  - Claire Sarsam <claire.sarsam@workiva.com>
  - Aaron Lademann <aaron.lademann@workiva.com>
  - Keal Jones <keal.jones@workiva.com>
  - Joe Bingham <joe.bingham@workiva.com>
  - Sydney Jodon <sydney.jodon@workiva.com>
description: Bindings of the ReactJS library for building interactive interfaces.
homepage: https://github.com/cleandart/react-dart
environment:
  sdk: '>=2.4.1 <3.0.0'
dependencies:
  js: ^0.6.0
  meta: ^1.1.6
dev_dependencies:
  build_runner: ^1.7.1
  build_test: ^0.10.9
  build_web_compilers: ^2.5.1
  dependency_validator: ^1.4.0
  matcher: ^0.12.5
  pedantic: ^1.8.0
  test: ^1.9.1
